---
ci:
  # https://pre-commit.ci/#configuration
  autoupdate_schedule: weekly
  autofix_prs: false

repos:
  - repo: https://github.com/psf/black
    # WARNING: rev should be the same as in `pyproject.toml`.
    rev: 21.9b0
    hooks:
      - id: black
