services:
  test-runner:
    build: .
    volumes:
      - .:/rdflib
    command: ["/rdflib/run_tests.sh"]

  test-runner-coverage:
    build: .
    volumes:
      - .:/rdflib
    command: ["/rdflib/run_tests_with_coverage_report.sh"]